name: Build-And-Run Tests

on: [push]

jobs:
  try_mac:
    runs-on: macos-latest
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Github Repo Checkout
        uses: actions/checkout@v2
      - name: Set Up Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          mamba-version: "*"
          channels: conda-forge,nodefaults
          auto-activate-base: false
          activate-environment: isce3-ci-sandbox
          environment-file: environment.yml
      - name: Configure CMAKE
        run: |
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=auto" \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            .
      - name: Build Project
        run: |
          cmake --build build --target install
          cd build
      - name: Test Project
        run: |
          ctest
