name: Build-And-Run Tests

on: [push]

jobs:
  build_and_test:
    strategy:
      fail-fast: false
      matrix:
        os: [macos-latest, ubuntu-latest]
    runs-on: ${{ matrix.os }}
    defaults:
      run:
        shell: bash -l {0}

    steps:
      - name: Github Repo Checkout
        uses: actions/checkout@v2
      - name: Set Up Python v3.9
        uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: Setup Environment
        uses: conda-incubator/setup-miniconda@v2
        with:
          channels: conda-forge,nodefaults
          auto-activate-base: false
          activate-environment: isce3-ci-sandbox
          environment-file: environment.yml
      - name: Configure CMAKE
        run: |
          env config vars set PYTHONPATH=$CONDA/envs/isce3-ci-sandbox/bin/python
          env config vars set LD_LIBRARY_PATH=$CONDA/envs/isce3-ci-sandbox/bin/ld
          if [ "$RUNNER_OS" == "macOS" ]; then
            env config vars set DYLD_LIBRARY_PATH=$CONDA/envs/isce3-ci-sandbox/bin/ld
            export REPO_PREFIX=/Users/runner/work/isce3-ci-sandbox/isce3-ci-sandbox

          elif [ "$RUNNER_OS" == "Linux" ]; then
            export REPO_PREFIX=/home/runner/work/isce3-ci-sandbox/isce3-ci-sandbox
          else
            echo "$RUNNER_OS not supported"
            exit 1
          fi
          cmake \
            -B build \
            -G Ninja \
            -DCMAKE_BUILD_TYPE=Release \
            -DCMAKE_CXX_FLAGS="-fdiagnostics-color=auto" \
            -DCMAKE_INSTALL_PREFIX=$REPO_PREFIX/install/prefix \
            -DCMAKE_PREFIX_PATH=$CONDA_PREFIX \
            .
      - name: Build Project
        run: |
          cmake --build build --target install --parallel
      - name: Test Project
        run: |
          if [ "$RUNNER_OS" == "macOS" ]; then
            echo $LD_LIBRARY_PATH
            echo $DYLD_LIBRARY_PATH
          fi
          ctest --test-dir build -E ".*stage_dem"
